### ISSUE TITLE
I get an error 

### ISSUE THREAD

**Issue by carlgoodier** [dwave-examples/portfolio-optimization#25] opened 2023-06-29 16:47 UTC
ValueError: API token not defined

**Comment by arcondello** [comment] 2023-06-29 16:50
Hi @carlgoodier , you need to [configure access to Leap](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html) before you can submit problems to the hybrid solver or quantum computer.

**Comment by carlgoodier** [comment] 2023-06-30 12:46
Thanks


Leap is not available to me…. I live in Thailand :(

**Comment by k8culver** [comment] 2024-11-20 23:40
Closing as this is not a bug

**Closed by k8culver** 2024-11-20 23:40 UTC
